databases:
  - name: card_blog
    databaseName: card_blog
    user: card_blog_user

services:
  - type: web
    name: api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: card_blog
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4