# Generated by Django 4.1.3 on 2023-01-15 17:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnews',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, max_length=200, quality=100, scale=None, size=[1920, 1080], upload_to='news_posts/'),
        ),
    ]
