# Generated by Django 4.1.3 on 2022-11-14 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_alter_photo_effect'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='images',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photologue.gallery'),
        ),
    ]
