# Generated by Django 4.1.3 on 2022-11-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_postnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnews',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
