# Generated by Django 4.1.3 on 2022-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_postnews_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postblog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Посты', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AddField(
            model_name='postblog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
