# Generated by Django 4.1.3 on 2022-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_postblog_options_postblog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
