# Generated by Django 4.1.3 on 2022-11-22 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('core', '0009_alter_postblog_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.CreateModel(
            name='RuTaggedItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.taggeditem',),
        ),
        migrations.AlterModelOptions(
            name='postnews',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_or_news', models.BooleanField()),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('post_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='core.postblog')),
                ('post_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='core.postnews')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='postblog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.RuTaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
