# Generated by Django 4.1.3 on 2022-11-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rutag_rutaggeditem_alter_postnews_options_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
