# Generated by Django 4.1.3 on 2022-11-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='choice',
            field=models.CharField(choices=[(models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='core.postblog'), 'blog'), (models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='core.postnews'), 'news')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
