# Generated by Django 4.1.3 on 2022-11-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_comments_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='blog_or_news',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post_blog',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post_news',
        ),
    ]
