# Generated by Django 4.1.3 on 2022-11-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_comments_post_comments_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='object_id',
        ),
    ]
