# Generated by Django 4.1.3 on 2022-11-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_comments_post_blog_alter_comments_post_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_blog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_blog', to='core.postblog'),
        ),
    ]
