# Generated by Django 4.1.3 on 2022-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_review_options_alter_comments_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='first_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
