# Generated by Django 4.1.3 on 2022-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_review_created_at_alter_review_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
