# Generated by Django 4.1.3 on 2023-01-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_postnews_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
